version: "3"
services:
  obeach:
    image: obeach
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/zis/.Xauthority:/root/.Xauthority
      - /home/zis/dev/datasets/:/usr/app/datasets/
    network_mode: host
    privileged: true
    ipc: host
    devices:
      - /dev/dri
